- name: Create Multi-brand pipeline jobs
  ansible.builtin.include_task:
    file: mjob.yml
    loop: "{{ mjobs }}"

- name: Create Single-brand pipeline jobs
  ansible.builtin.include_task:
    file: sjob.yml
    loop: "{{ sjobs }}"

