- name: Copy Config File - {{ item.job_name }}
  ansible.builtin.template:
    src: mjob.xml
  dest: /tmp/mjob.xml

- name: Create job - {{ item.job_name }}
  community.general.jenkins_job:
     config: "{{ lookup('file', '/tmp/mjob.xml') }}"
     name: "{{ item.job_name }}"
     password: admin123
     url: http://172.31.16.131:8080
     user: admin
